import { useEffect, useState } from 'react'
import { api } from '../services/api'
import { useAuth } from '../context/AuthContext'

const blank = { title:'', company:'', location:'', type:'FULL_TIME', salary:'', description:'', requirements:'' }
export default function RecruiterDashboard(){
  const { user }=useAuth(); const [jobs,setJobs]=useState([]); const [form,setForm]=useState({...blank,company:user.companyName||''}); const [error,setError]=useState(''); const [msg,setMsg]=useState(''); const [apps,setApps]=useState([]); const [selectedJob,setSelectedJob]=useState(null)
  const load=()=>api('/jobs/mine').then(setJobs).catch(e=>setError(e.message)); useEffect(load,[])
  const create=async e=>{e.preventDefault();setError('');setMsg('');try{await api('/jobs',{method:'POST',body:JSON.stringify(form)});setForm({...blank,company:user.companyName||''});setMsg('Job published successfully.');load()}catch(e){setError(e.message)}}
  const viewApplicants=async job=>{setSelectedJob(job);try{setApps(await api(`/applications/job/${job.id}`))}catch(e){setError(e.message)}}
  const updateStatus=async (id,status)=>{try{await api(`/applications/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});setApps(await api(`/applications/job/${selectedJob.id}`))}catch(e){setError(e.message)}}
  const closeJob=async id=>{if(!confirm('Close this job?'))return;try{await api(`/jobs/${id}`,{method:'DELETE'});load()}catch(e){setError(e.message)}}
  return <main className="container page"><div className="page-head"><div><span className="eyebrow">RECRUITER DASHBOARD</span><h1>Hiring workspace</h1><p className="muted">Publish jobs and manage applicants.</p></div></div>{msg&&<div className="success">{msg}</div>}{error&&<div className="alert">{error}</div>}
  <div className="dashboard-grid"><form className="panel form-panel" onSubmit={create}><h2>Post a new job</h2><div className="form-grid"><label>Job title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Company<input required value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label><label>Location<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>FULL_TIME</option><option>PART_TIME</option><option>INTERNSHIP</option><option>CONTRACT</option><option>REMOTE</option></select></label><label className="wide">Salary<input value={form.salary} onChange={e=>setForm({...form,salary:e.target.value})} placeholder="e.g. 4-6 LPA"/></label><label className="wide">Description<textarea required rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="wide">Requirements<textarea rows="4" value={form.requirements} onChange={e=>setForm({...form,requirements:e.target.value})}/></label></div><button className="btn btn-primary">Publish job</button></form>
  <section className="panel"><h2>Your job posts</h2>{jobs.map(j=><div className="recruit-job" key={j.id}><div><b>{j.title}</b><small>{j.company} • {j.location}</small></div><div className="row-actions"><button className="btn btn-ghost" onClick={()=>viewApplicants(j)}>Applicants</button><button className="btn btn-danger" onClick={()=>closeJob(j.id)}>Close</button></div></div>)}{!jobs.length&&<div className="empty">No jobs posted yet.</div>}</section></div>
  {selectedJob&&<section className="panel applicants"><div className="panel-head"><h2>Applicants — {selectedJob.title}</h2><button className="btn btn-ghost" onClick={()=>setSelectedJob(null)}>Close</button></div>{apps.length?<div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Email</th><th>Status</th><th>Change status</th></tr></thead><tbody>{apps.map(a=><tr key={a.id}><td>{a.candidate.name}</td><td>{a.candidate.email}</td><td><span className={`status ${a.status.toLowerCase()}`}>{a.status}</span></td><td><select value={a.status} onChange={e=>updateStatus(a.id,e.target.value)}><option>APPLIED</option><option>SHORTLISTED</option><option>INTERVIEW</option><option>SELECTED</option><option>REJECTED</option></select></td></tr>)}</tbody></table></div>:<div className="empty">No applications for this job yet.</div>}</section>}
  </main>
}
